### ISSUE TITLE
Reproducing results in cifar10

### ISSUE THREAD

**Issue by sagejiaweili** [SenWu/dauphin#4]
Hi, I try the nice code and it is easy to run. But I did not get the exact numbers reported in the paper at the moment. Specifically, I got 97.72 for multi 4 loss 1 setting, while the reported number is 97.89. For multi 8 loss 4 setting, I got 98.10 while the reported one is 98.16. I would like to know whether I miss something important or it is just the variance. Thx

**Comment by senwu** [comment]
Hi @sagejiaweili,

Thanks for your interest in our work.
I think it's just the variance and as mentioned in the paper, we report the average number over different runs. You can also run our released checkpoints to double check.

Thanks,
Sen
